### ISSUE TITLE
Insertion Sort in Java Script

### ISSUE THREAD

**Issue by Uditha95** [Uditha95/AlgorithmHub#4]
Implement Insertion Sort in Java Script and update README.md file

**Comment by VolatianaYuliana** [comment]
Hi @Uditha95 I would like to work on this one

**Comment by sewwandikarunarathna** [comment]
Can you please assign me for this?

**Comment by Uditha95** [comment]
@sewwandikarunarathna  Welcome! send PR after fix it.

**Comment by Uditha95** [comment]
@VolatianaYuliana . Can you fix #6
